// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0L8Z92QsnXY7KYqPXeIZnGWKxByk42JQ',
    appId: '1:170673081044:web:d1585c26faf5611e6a4941',
    messagingSenderId: '170673081044',
    projectId: 'ticket-master-542ef',
    authDomain: 'ticket-master-542ef.firebaseapp.com',
    storageBucket: 'ticket-master-542ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDys29LNAv0srCoTht9IJ3ONGbHWjmm3CY',
    appId: '1:170673081044:android:4ea11b216e73321c6a4941',
    messagingSenderId: '170673081044',
    projectId: 'ticket-master-542ef',
    storageBucket: 'ticket-master-542ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtTD7wDUTszU0zj93aEIe6rBYDhBCbeAI',
    appId: '1:170673081044:ios:c5ebbfba72875ff96a4941',
    messagingSenderId: '170673081044',
    projectId: 'ticket-master-542ef',
    storageBucket: 'ticket-master-542ef.firebasestorage.app',
    iosClientId: '170673081044-vfn6g4eos0hl504e19nt246fp8sulovb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtTD7wDUTszU0zj93aEIe6rBYDhBCbeAI',
    appId: '1:170673081044:ios:c5ebbfba72875ff96a4941',
    messagingSenderId: '170673081044',
    projectId: 'ticket-master-542ef',
    storageBucket: 'ticket-master-542ef.firebasestorage.app',
    iosClientId: '170673081044-vfn6g4eos0hl504e19nt246fp8sulovb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0L8Z92QsnXY7KYqPXeIZnGWKxByk42JQ',
    appId: '1:170673081044:web:9dcea7ae514227ed6a4941',
    messagingSenderId: '170673081044',
    projectId: 'ticket-master-542ef',
    authDomain: 'ticket-master-542ef.firebaseapp.com',
    storageBucket: 'ticket-master-542ef.firebasestorage.app',
  );
}
